name: Animation Grid
favicon: null
layout_spectrum: 0.24360791011713445
typography_spectrum: 0.2886886971537024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9859980787150562
  lightness: 0.5229494862724096
  saturation: 0.045675081899389625
  rhythmicContrast: 0.5659786218311638
purpose: []
